import { Course, User, TutorListing, StudyGroup } from "@/types";

export const mockCourses: Course[] = [
  {
    id: "cs300",
    department: "COMP SCI",
    courseNumber: 300,
    courseTitle: "Programming II",
    lectureNumber: "001",
    lectureTime: "MWF 9:55-10:45 AM",
    professorName: "Prof. Smith",
    semester: "Fall 2025",
    difficulty: 3,
    topics: ["Data Structures", "Algorithms", "OOP"],
  },
  {
    id: "cs400",
    department: "COMP SCI",
    courseNumber: 400,
    courseTitle: "Programming III",
    lectureNumber: "002",
    lectureTime: "TuTh 1:00-2:15 PM",
    professorName: "Prof. Johnson",
    semester: "Fall 2025",
    difficulty: 4,
    topics: ["Advanced Data Structures", "Graph Algorithms", "Dynamic Programming"],
  },
  {
    id: "math340",
    department: "MATH",
    courseNumber: 340,
    courseTitle: "Linear Algebra",
    lectureNumber: "001",
    lectureTime: "MWF 11:00-11:50 AM",
    professorName: "Prof. Williams",
    semester: "Fall 2025",
    difficulty: 4,
    topics: ["Matrix Operations", "Eigenvalues", "Vector Spaces"],
  },
  {
    id: "stat240",
    department: "STAT",
    courseNumber: 240,
    courseTitle: "Intro to Statistics",
    lectureNumber: "003",
    lectureTime: "TuTh 9:30-10:45 AM",
    professorName: "Prof. Davis",
    semester: "Fall 2025",
    difficulty: 2,
    topics: ["Probability", "Distributions", "Hypothesis Testing"],
  },
];

export const mockTutors: TutorListing[] = [
  {
    id: "tutor-1",
    tutorUserId: "user-1",
    tutor: {
      id: "user-1",
      name: "Sarah Chen",
      email: "schen@wisc.edu",
      role: "tutor",
      major: "Computer Science",
      graduationYear: 2025,
      department: "COMP SCI",
      courses: [mockCourses[0], mockCourses[1]],
      walletPublicKey: "3Fsxabc1239QaT",
      rating: 4.8,
      ratingCount: 24,
      bio: "CS major with a passion for teaching. Specializing in data structures and algorithms.",
      hourlyRate: 30,
      availability: ["Monday", "Wednesday", "Friday"],
      locations: ["Memorial Library", "CS Building", "Online"],
      isTutor: true,
      studentId: "1234567890",
    },
    coursesOffered: [mockCourses[0], mockCourses[1]],
    hourlyRate: 30,
    rating: 4.8,
    ratingCount: 24,
    shortDescription: "Experienced CS tutor specializing in data structures and algorithms",
    availableModes: ["online", "in-person"],
    campusLocations: ["Memorial Library", "CS Building"],
    tags: ["Exam prep", "Homework help", "Concept review"],
  },
  {
    id: "tutor-2",
    tutorUserId: "user-2",
    tutor: {
      id: "user-2",
      name: "Michael Rodriguez",
      email: "mrodriguez@wisc.edu",
      role: "tutor",
      major: "Mathematics",
      graduationYear: 2026,
      department: "MATH",
      courses: [mockCourses[2]],
      walletPublicKey: "4Gtyxyz7899RbU",
      rating: 4.9,
      ratingCount: 31,
      bio: "Math major with experience in linear algebra and calculus tutoring.",
      hourlyRate: 25,
      availability: ["Tuesday", "Thursday"],
      locations: ["College Library", "Online"],
      isTutor: true,
      studentId: "0987654321",
    },
    coursesOffered: [mockCourses[2]],
    hourlyRate: 25,
    rating: 4.9,
    ratingCount: 31,
    shortDescription: "Patient and thorough math tutor, great with linear algebra",
    availableModes: ["online", "in-person", "hybrid"],
    campusLocations: ["College Library"],
    tags: ["Concept review", "Problem-solving"],
  },
];

export const mockStudyGroups: StudyGroup[] = [
  {
    id: "group-1",
    course: mockCourses[0],
    groupName: "CS300 Study Squad",
    leaderUserId: "user-3",
    leader: {
      id: "user-3",
      name: "Emily Taylor",
      email: "etaylor@wisc.edu",
      role: "student",
      major: "Computer Science",
      graduationYear: 2026,
      department: "COMP SCI",
      courses: [mockCourses[0]],
      walletPublicKey: null,
      rating: 0,
      ratingCount: 0,
      bio: "",
      hourlyRate: null,
      availability: [],
      locations: [],
      isTutor: false,
      studentId: "1122334455",
    },
    maxMembers: 6,
    currentMembers: 4,
    meetingTimes: ["Wednesday 6:00-8:00 PM", "Sunday 2:00-4:00 PM"],
    meetingLocation: "CS Building, Room 1240",
    groupType: "exam-focused",
    description: "Focused group preparing for midterm exams. We work through practice problems together.",
  },
  {
    id: "group-2",
    course: mockCourses[2],
    groupName: "Linear Algebra Workshop",
    leaderUserId: "user-4",
    leader: {
      id: "user-4",
      name: "David Kim",
      email: "dkim@wisc.edu",
      role: "student",
      major: "Mathematics",
      graduationYear: 2025,
      department: "MATH",
      courses: [mockCourses[2]],
      walletPublicKey: null,
      rating: 0,
      ratingCount: 0,
      bio: "",
      hourlyRate: null,
      availability: [],
      locations: [],
      isTutor: false,
      studentId: "5566778899",
    },
    maxMembers: 8,
    currentMembers: 6,
    meetingTimes: ["Tuesday 7:00-9:00 PM", "Friday 3:00-5:00 PM"],
    meetingLocation: "Online via Zoom",
    groupType: "serious",
    description: "Weekly study sessions covering all topics. Great for staying on track!",
  },
];
