// This will be generated by Anchor after building
// For now, this is a placeholder structure
export const IDL: any = {
  version: "0.1.0",
  name: "badger_tutors",
  instructions: [
    {
      name: "paySolana",
      accounts: [
        { name: "student", isMut: true, isSigner: true },
        { name: "tutor", isMut: false, isSigner: false },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "escrowAccount", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "sessionId", type: "string" },
        { name: "amount", type: "u64" },
      ],
    },
    {
      name: "confirmSession",
      accounts: [
        { name: "confirmer", isMut: true, isSigner: true },
        { name: "escrow", isMut: true, isSigner: false },
      ],
      args: [{ name: "isStudent", type: "bool" }],
    },
    {
      name: "receiveSolana",
      accounts: [
        { name: "tutor", isMut: true, isSigner: true },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "escrowAccount", isMut: true, isSigner: false },
      ],
      args: [],
    },
    {
      name: "updateRating",
      accounts: [
        { name: "student", isMut: true, isSigner: true },
        { name: "tutor", isMut: false, isSigner: false },
        { name: "escrow", isMut: false, isSigner: false },
        { name: "ratingAccount", isMut: true, isSigner: false },
        { name: "tutorRating", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "rating", type: "u8" },
        { name: "reviewText", type: "string" },
      ],
    },
    {
      name: "cancelSession",
      accounts: [
        { name: "student", isMut: true, isSigner: true },
        { name: "escrow", isMut: true, isSigner: false },
        { name: "escrowAccount", isMut: true, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "EscrowAccount",
      type: {
        kind: "struct",
        fields: [
          { name: "student", type: "publicKey" },
          { name: "tutor", type: "publicKey" },
          { name: "sessionId", type: "string" },
          { name: "amount", type: "u64" },
          { name: "status", type: { defined: "EscrowStatus" } },
          { name: "confirmedByStudent", type: "bool" },
          { name: "confirmedByTutor", type: "bool" },
          { name: "studentConfirmedAt", type: { option: "i64" } },
          { name: "tutorConfirmedAt", type: { option: "i64" } },
          { name: "createdAt", type: "i64" },
          { name: "confirmationDeadline", type: "i64" },
          { name: "releasedAt", type: { option: "i64" } },
        ],
      },
    },
    {
      name: "RatingAccount",
      type: {
        kind: "struct",
        fields: [
          { name: "tutor", type: "publicKey" },
          { name: "student", type: "publicKey" },
          { name: "sessionId", type: "string" },
          { name: "rating", type: "u8" },
          { name: "reviewText", type: "string" },
          { name: "createdAt", type: "i64" },
        ],
      },
    },
    {
      name: "TutorRating",
      type: {
        kind: "struct",
        fields: [
          { name: "tutor", type: "publicKey" },
          { name: "totalRatings", type: "u64" },
          { name: "totalScore", type: "u64" },
          { name: "averageRating", type: "f64" },
        ],
      },
    },
  ],
  types: [
    {
      name: "EscrowStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Locked" },
          { name: "AwaitingConfirmation" },
          { name: "Released" },
          { name: "Cancelled" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "EscrowNotLocked", msg: "Escrow is not in locked status" },
    { code: 6001, name: "EscrowAlreadyReleased", msg: "Escrow has already been released" },
    { code: 6002, name: "CannotReleaseYet", msg: "Cannot release payment yet" },
    { code: 6003, name: "InvalidRating", msg: "Invalid rating (must be 1-5)" },
    { code: 6004, name: "PaymentNotReleased", msg: "Payment has not been released yet" },
    { code: 6005, name: "Unauthorized", msg: "Unauthorized action" },
    { code: 6006, name: "CannotCancel", msg: "Cannot cancel session in current status" },
  ],
};

export type BadgerTutors = {
  version: "0.1.0";
  name: "badger_tutors";
  instructions: typeof IDL.instructions;
  accounts: typeof IDL.accounts;
  types: typeof IDL.types;
  errors: typeof IDL.errors;
};

